from bosdyn.client.frame_helpers import GRAV_ALIGNED_BODY_FRAME_NAME, ODOM_FRAME_NAME, GROUND_PLANE_FRAME_NAME, HAND_FRAME_NAME
print(ODOM_FRAME_NAME)
print(GRAV_ALIGNED_BODY_FRAME_NAME)
print(GROUND_PLANE_FRAME_NAME)
print(HAND_FRAME_NAME)



print(2//3)
print(2 % 3)